// Code generated by protoc-gen-go. DO NOT EDIT.
// source: LoginTest.proto

package LoginTest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d18a4d45edf1a1e, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Access               bool     `protobuf:"varint,2,opt,name=access,proto3" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d18a4d45edf1a1e, []int{1}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginReply) GetAccess() bool {
	if m != nil {
		return m.Access
	}
	return false
}

type LogoutRequest struct {
	// This field only contains this title
	Timeoflogout string `protobuf:"bytes,1,opt,name=timeoflogout,proto3" json:"timeoflogout,omitempty"`
	// This is the title
	//
	// This is the "Description" of field test
	// you can use as many newlines as you want
	//
	//
	// it will still format the same in the table
	Test int32 `protobuf:"varint,2,opt,name=test,proto3" json:"test,omitempty"`
	// Array title
	Stringarray          []string `protobuf:"bytes,3,rep,name=stringarray,proto3" json:"stringarray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d18a4d45edf1a1e, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetTimeoflogout() string {
	if m != nil {
		return m.Timeoflogout
	}
	return ""
}

func (m *LogoutRequest) GetTest() int32 {
	if m != nil {
		return m.Test
	}
	return 0
}

func (m *LogoutRequest) GetStringarray() []string {
	if m != nil {
		return m.Stringarray
	}
	return nil
}

type LogoutReply struct {
	// Message that displays whether the logout was succesful or not
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReply) Reset()         { *m = LogoutReply{} }
func (m *LogoutReply) String() string { return proto.CompactTextString(m) }
func (*LogoutReply) ProtoMessage()    {}
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d18a4d45edf1a1e, []int{3}
}

func (m *LogoutReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReply.Unmarshal(m, b)
}
func (m *LogoutReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReply.Marshal(b, m, deterministic)
}
func (m *LogoutReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReply.Merge(m, src)
}
func (m *LogoutReply) XXX_Size() int {
	return xxx_messageInfo_LogoutReply.Size(m)
}
func (m *LogoutReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReply.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReply proto.InternalMessageInfo

func (m *LogoutReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginTest.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginTest.LoginReply")
	proto.RegisterType((*LogoutRequest)(nil), "LoginTest.LogoutRequest")
	proto.RegisterType((*LogoutReply)(nil), "LoginTest.LogoutReply")
}

func init() { proto.RegisterFile("LoginTest.proto", fileDescriptor_6d18a4d45edf1a1e) }

var fileDescriptor_6d18a4d45edf1a1e = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xd6, 0xb6, 0x74, 0xe9, 0xba, 0x45, 0x20, 0x4b, 0x2d, 0xab, 0x80, 0x84, 0xc9, 0x85, 0x0a,
	0x91, 0x8d, 0x80, 0x5b, 0x0f, 0x48, 0x45, 0x6a, 0x4f, 0x95, 0x10, 0xa1, 0x12, 0x67, 0xaf, 0x33,
	0xeb, 0x58, 0x4a, 0x3c, 0xc6, 0x9e, 0xec, 0x92, 0x2b, 0x8f, 0x00, 0x8f, 0xc3, 0x81, 0x87, 0xe0,
	0x15, 0x78, 0x08, 0x8e, 0x68, 0xbd, 0x49, 0x7f, 0x54, 0x04, 0x27, 0xcf, 0xf7, 0x7d, 0xe3, 0x6f,
	0xc6, 0xe3, 0x61, 0xf7, 0xcf, 0x51, 0x1b, 0x7b, 0x01, 0x81, 0x66, 0xce, 0x23, 0x21, 0x9f, 0x5c,
	0x12, 0xc9, 0x63, 0x8d, 0xa8, 0x6b, 0xc8, 0xa5, 0x33, 0xb9, 0xb4, 0x16, 0x49, 0x92, 0x41, 0x1b,
	0x36, 0x89, 0xc9, 0x8b, 0x78, 0xa8, 0x4c, 0x83, 0xcd, 0xc2, 0x4a, 0x6a, 0x0d, 0x3e, 0x47, 0x17,
	0x33, 0x6e, 0x67, 0xa7, 0x67, 0x6c, 0x3f, 0x1a, 0x17, 0xf0, 0xa9, 0x85, 0x40, 0x3c, 0x61, 0xbb,
	0x6d, 0x00, 0x6f, 0x65, 0x03, 0xd3, 0x91, 0x18, 0x1d, 0x4d, 0x8a, 0x4b, 0xbc, 0xd6, 0x9c, 0x0c,
	0x61, 0x85, 0xbe, 0x9c, 0x6e, 0x6d, 0xb4, 0x01, 0xa7, 0x6f, 0x18, 0xeb, 0x7d, 0x5c, 0xdd, 0xf1,
	0x29, 0xbb, 0xdb, 0x40, 0x08, 0x52, 0x0f, 0x26, 0x03, 0xe4, 0x87, 0x6c, 0x2c, 0x95, 0x82, 0x10,
	0xa2, 0xc3, 0x6e, 0xd1, 0xa3, 0xd4, 0xb0, 0x7b, 0xe7, 0xa8, 0xb1, 0xa5, 0xa1, 0x91, 0x94, 0xed,
	0x93, 0x69, 0x00, 0x17, 0x75, 0xa4, 0x7b, 0x9f, 0x1b, 0x1c, 0xe7, 0xec, 0x0e, 0x41, 0xa0, 0x68,
	0xb5, 0x53, 0xc4, 0x98, 0x0b, 0xb6, 0x17, 0xc8, 0x1b, 0xab, 0xa5, 0xf7, 0xb2, 0x9b, 0x6e, 0x8b,
	0xed, 0xa3, 0x49, 0x71, 0x9d, 0x4a, 0x9f, 0xb1, 0xbd, 0xa1, 0xd4, 0x3f, 0x7b, 0x7d, 0xf5, 0x7b,
	0x8b, 0xed, 0xc4, 0x47, 0xf1, 0x8b, 0x21, 0x78, 0x38, 0xbb, 0xfa, 0x97, 0xeb, 0x73, 0x4b, 0x0e,
	0x6e, 0x0b, 0xae, 0xee, 0xd2, 0x47, 0x5f, 0x7e, 0xfe, 0xfa, 0xb6, 0x75, 0x90, 0x3e, 0xc8, 0x97,
	0x2f, 0x73, 0xf8, 0x2c, 0x1b, 0x57, 0x43, 0x0e, 0xaa, 0xc2, 0xe3, 0xd1, 0x73, 0xfe, 0x91, 0x8d,
	0x37, 0x8d, 0xf0, 0xe9, 0xcd, 0xdb, 0x57, 0x63, 0x48, 0x0e, 0xff, 0xa2, 0xfc, 0xcf, 0x38, 0xf9,
	0x31, 0xfa, 0x7a, 0xf2, 0x7d, 0xc4, 0x17, 0x27, 0x6f, 0x0d, 0xbd, 0x5b, 0x9c, 0x2e, 0xc1, 0x77,
	0x54, 0x19, 0xab, 0x3f, 0x80, 0x5f, 0x1a, 0x05, 0xa2, 0x84, 0xa0, 0xbc, 0x89, 0x3b, 0x21, 0xb2,
	0x4c, 0xac, 0x2a, 0xa3, 0x2a, 0x11, 0x2a, 0x6c, 0xeb, 0x52, 0x58, 0x24, 0x31, 0x07, 0xd1, 0x06,
	0x28, 0x85, 0xb1, 0xc2, 0xd5, 0x52, 0x81, 0xc0, 0x85, 0xa0, 0x0a, 0x44, 0x89, 0xaa, 0x6d, 0xc0,
	0x6e, 0x36, 0x48, 0x28, 0x6c, 0xd6, 0xe0, 0x69, 0xf2, 0x9e, 0x3d, 0x39, 0x33, 0xb6, 0x14, 0xd8,
	0x92, 0x68, 0xd0, 0x83, 0x90, 0xf3, 0x75, 0x78, 0xaa, 0x2a, 0xec, 0x2b, 0xf2, 0x59, 0x45, 0xe4,
	0xc2, 0x71, 0x9e, 0x6b, 0x43, 0x55, 0x3b, 0x9f, 0x29, 0x6c, 0x72, 0xed, 0x9d, 0xca, 0x40, 0x61,
	0xe8, 0x02, 0x41, 0x0f, 0xb5, 0x24, 0x58, 0xc9, 0x6e, 0x3e, 0x8e, 0xdb, 0xf9, 0xfa, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0xe9, 0x70, 0x0f, 0x07, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	// {{import "documentation.md"}}
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// Logout
	//
	// {{.MethodDescriptorProto.Name}} is a call with the method(s) {{$first := true}}{{range .Bindings}}{{if $first}}{{$first = false}}{{else}}, {{end}}{{.HTTPMethod}}{{end}} within the "{{.Service.Name}}" service.
	// It takes in "{{.RequestType.Name}}" and returns a "{{.ResponseType.Name}}".
	//
	// ## {{.RequestType.Name}}
	// | Field ID    | Name      | Type                                                       | Description                  |
	// | ----------- | --------- | ---------------------------------------------------------  | ---------------------------- | {{range .RequestType.Fields}}
	// | {{.Number}} | {{.Name}} | {{if eq .Label.String "LABEL_REPEATED"}}[]{{end}}{{.Type}} | {{fieldcomments .Message .}} | {{end}}
	//
	// ## {{.ResponseType.Name}}
	// | Field ID    | Name      | Type                                                       | Description                  |
	// | ----------- | --------- | ---------------------------------------------------------- | ---------------------------- | {{range .ResponseType.Fields}}
	// | {{.Number}} | {{.Name}} | {{if eq .Label.String "LABEL_REPEATED"}}[]{{end}}{{.Type}} | {{fieldcomments .Message .}} | {{end}}
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/LoginTest.Login/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutReply, error) {
	out := new(LogoutReply)
	err := c.cc.Invoke(ctx, "/LoginTest.Login/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	// {{import "documentation.md"}}
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// Logout
	//
	// {{.MethodDescriptorProto.Name}} is a call with the method(s) {{$first := true}}{{range .Bindings}}{{if $first}}{{$first = false}}{{else}}, {{end}}{{.HTTPMethod}}{{end}} within the "{{.Service.Name}}" service.
	// It takes in "{{.RequestType.Name}}" and returns a "{{.ResponseType.Name}}".
	//
	// ## {{.RequestType.Name}}
	// | Field ID    | Name      | Type                                                       | Description                  |
	// | ----------- | --------- | ---------------------------------------------------------  | ---------------------------- | {{range .RequestType.Fields}}
	// | {{.Number}} | {{.Name}} | {{if eq .Label.String "LABEL_REPEATED"}}[]{{end}}{{.Type}} | {{fieldcomments .Message .}} | {{end}}
	//
	// ## {{.ResponseType.Name}}
	// | Field ID    | Name      | Type                                                       | Description                  |
	// | ----------- | --------- | ---------------------------------------------------------- | ---------------------------- | {{range .ResponseType.Fields}}
	// | {{.Number}} | {{.Name}} | {{if eq .Label.String "LABEL_REPEATED"}}[]{{end}}{{.Type}} | {{fieldcomments .Message .}} | {{end}}
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
}

// UnimplementedLoginServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (*UnimplementedLoginServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedLoginServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoginTest.Login/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Login_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoginTest.Login/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LoginTest.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Login_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Login_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "LoginTest.proto",
}
