// Code generated by protoc-gen-go. DO NOT EDIT.
// source: markdown.proto

package LoginTest

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// LoginRequest
//
// ## I can use this to document LoginRequest
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c2b955fff2fc13, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// LoginReply
//
// ## I can use this to document LoginReply
type LoginReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Access               bool     `protobuf:"varint,2,opt,name=access,proto3" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReply) Reset()         { *m = LoginReply{} }
func (m *LoginReply) String() string { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()    {}
func (*LoginReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c2b955fff2fc13, []int{1}
}

func (m *LoginReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReply.Unmarshal(m, b)
}
func (m *LoginReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReply.Marshal(b, m, deterministic)
}
func (m *LoginReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReply.Merge(m, src)
}
func (m *LoginReply) XXX_Size() int {
	return xxx_messageInfo_LoginReply.Size(m)
}
func (m *LoginReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReply proto.InternalMessageInfo

func (m *LoginReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *LoginReply) GetAccess() bool {
	if m != nil {
		return m.Access
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "LoginTest.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "LoginTest.LoginReply")
}

func init() { proto.RegisterFile("markdown.proto", fileDescriptor_d2c2b955fff2fc13) }

var fileDescriptor_d2c2b955fff2fc13 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x8a, 0x14, 0x31,
	0x14, 0x86, 0xa9, 0x06, 0xc7, 0x99, 0x20, 0x22, 0x05, 0xa3, 0x4d, 0x29, 0xf8, 0xec, 0x95, 0x88,
	0x55, 0x41, 0xdd, 0xcd, 0x42, 0x18, 0x61, 0x66, 0x25, 0x88, 0xed, 0x5c, 0x20, 0x9d, 0x7a, 0x9d,
	0x04, 0x2b, 0x79, 0x31, 0x2f, 0xd5, 0x65, 0x6d, 0x3d, 0x82, 0x1e, 0xc0, 0x83, 0xb8, 0xf0, 0x10,
	0x5e, 0xc1, 0x83, 0x48, 0x57, 0x77, 0x0f, 0x42, 0xaf, 0xea, 0x7d, 0xfc, 0x3f, 0x5f, 0x25, 0x2f,
	0xe2, 0xbe, 0x57, 0xe9, 0x73, 0x4b, 0x43, 0x68, 0x62, 0xa2, 0x4c, 0xe5, 0xd9, 0x7b, 0x32, 0x2e,
	0xdc, 0x20, 0xe7, 0xea, 0x89, 0x21, 0x32, 0x1d, 0x4a, 0x15, 0x9d, 0x54, 0x21, 0x50, 0x56, 0xd9,
	0x51, 0xe0, 0x5d, 0xb1, 0x7a, 0x39, 0x7d, 0x74, 0x6d, 0x30, 0xd4, 0x3c, 0x28, 0x63, 0x30, 0x49,
	0x8a, 0x53, 0xe3, 0xb8, 0xbd, 0xb8, 0x16, 0xf7, 0x26, 0xf1, 0x12, 0xbf, 0xf4, 0xc8, 0xb9, 0xac,
	0xc4, 0x69, 0xcf, 0x98, 0x82, 0xf2, 0x38, 0x2f, 0xa0, 0x78, 0x7e, 0xb6, 0xbc, 0xe5, 0x6d, 0x16,
	0x15, 0xf3, 0x40, 0xa9, 0x9d, 0xcf, 0x76, 0xd9, 0x81, 0x17, 0x6f, 0x85, 0xd8, 0x7b, 0x62, 0x37,
	0x96, 0x73, 0x71, 0xd7, 0x23, 0xb3, 0x32, 0x07, 0xc9, 0x01, 0xcb, 0x87, 0xe2, 0x44, 0x69, 0x8d,
	0xcc, 0x93, 0xe1, 0x74, 0xb9, 0xa7, 0xd7, 0x3f, 0x67, 0xe2, 0xce, 0x24, 0x28, 0x6f, 0x0e, 0xc3,
	0xa3, 0xe6, 0xf6, 0xca, 0xcd, 0xff, 0x67, 0xac, 0xce, 0x8f, 0x83, 0xd8, 0x8d, 0x8b, 0xc7, 0xdf,
	0xfe, 0xfc, 0xfd, 0x31, 0x3b, 0x5f, 0x3c, 0x90, 0x9b, 0x57, 0x12, 0xbf, 0x2a, 0x1f, 0x3b, 0x94,
	0xa8, 0x2d, 0x5d, 0x14, 0x2f, 0xaa, 0xdf, 0xc5, 0xf7, 0xcb, 0x5f, 0x45, 0xb9, 0xbe, 0x7c, 0xe7,
	0xf2, 0x87, 0xf5, 0xd5, 0x06, 0xd3, 0x98, 0xad, 0x0b, 0xe6, 0x13, 0xa6, 0x8d, 0xd3, 0x08, 0x2d,
	0xb2, 0x4e, 0x6e, 0x5a, 0x13, 0xd4, 0x35, 0x0c, 0xd6, 0x69, 0x0b, 0x6c, 0xa9, 0xef, 0x5a, 0x08,
	0x94, 0x61, 0x85, 0xd0, 0x33, 0xb6, 0xe0, 0x02, 0xc4, 0x4e, 0x69, 0x04, 0x5a, 0x43, 0xb6, 0x08,
	0x2d, 0xe9, 0xde, 0x63, 0xd8, 0x2d, 0x15, 0x34, 0xf9, 0x2d, 0x3c, 0xab, 0x3e, 0x8a, 0xa7, 0xd7,
	0x2e, 0xb4, 0x40, 0x7d, 0x06, 0x4f, 0x09, 0x41, 0xad, 0xb6, 0xe3, 0x95, 0xb6, 0xb4, 0xff, 0x63,
	0xd9, 0xd8, 0x9c, 0x23, 0x5f, 0x48, 0x69, 0x5c, 0xb6, 0xfd, 0xaa, 0xd1, 0xe4, 0xa5, 0x49, 0x51,
	0xd7, 0xa8, 0x89, 0x47, 0xce, 0xb8, 0x47, 0xa3, 0x32, 0x0e, 0x6a, 0x5c, 0x9d, 0x4c, 0x0f, 0xf6,
	0xe6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x2c, 0x0f, 0xdc, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoginClient is the client API for Login service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoginClient interface {
	// Login
	//
	// ## I can use this to document Login
	// ### Test
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/LoginTest.Login/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginServer is the server API for Login service.
type LoginServer interface {
	// Login
	//
	// ## I can use this to document Login
	// ### Test
	Login(context.Context, *LoginRequest) (*LoginReply, error)
}

// UnimplementedLoginServer can be embedded to have forward compatible implementations.
type UnimplementedLoginServer struct {
}

func (*UnimplementedLoginServer) Login(ctx context.Context, req *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LoginTest.Login/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "LoginTest.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Login_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "markdown.proto",
}
